# Simple workflow for deploying static content to GitHub Pages
name: deploy

on:
  push:
    branches:
      - main
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Allow one concurrent deployment
concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  checks:
    uses: StreamingTime/StreamTime/.github/workflows/elm-checks.yml@${{GITHUB_SHA}}
  deploy-dummy:
    runs-on: ubuntu-latest
    needs: [checks]
    steps:
      - run: echo "Deploy stuff 🚀"
  # deploy:
  #     environment:
  #         name: github-pages
  #         url: ${{ steps.deployment.outputs.page_url }}
  #     runs-on: ubuntu-latest
      
  #     steps:
  #       - uses: actions/checkout@v3

  #       - run: yarn --frozen-lockfile

  #       - name: Add elm, elm-tailwind-modules and elm-test to path
  #         run: yarn bin >> $GITHUB_PATH

  #       - name: Generate tailwind code
  #         run: elm-tailwind-modules --dir ./gen --tailwind-config tailwind.config.js

  #       - name: Create config file
  #         run: cp src/TwitchConfig.elm.example src/TwitchConfig.elm
        
  #       - name: Insert twitch client id
  #         run: sed -i 's/twitch_client_id/${{ secrets.TWITCH_CLIENT_ID }}/g' src/TwitchConfig.elm
        
  #       - name: Create dist folder
  #         run: mkdir dist

  #       - name: Build app
  #         run: elm make src/Main.elm --optimize --output=dist/main.js
          
  #       - name: Copy assets
  #         run: cp -r assets/ dist/
        
  #       - run: cp index.html dist/
        
  #       - run: cp favicon.ico dist/
        
  #       - run: ls dist
      
      # deploy stuff
      
        # - name: Setup Pages
        #   uses: actions/configure-pages@v2
        # - name: Upload artifact
        #   uses: actions/upload-pages-artifact@v1
        #   with:
        #     path: 'dist'
        # - name: Deploy to GitHub Pages
        #   id: deployment
        #   uses: actions/deploy-pages@v1
