name: elm-review

on:
  workflow_call:
    secrets:
        gh_token:
          required: true

jobs:
  elm_review:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - run: yarn --frozen-lockfile

      - name: Add elm-review, elm and elm-format to path
        run: yarn bin >> $GITHUB_PATH

      - uses: sparksp/elm-review-action@v1.0.9
        env:
          GITHUB_TOKEN: ${{ secrets.gh_token }}
